name: build-debian

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**'
      - '!README.md'
      - '!LICENSE'
  pull_request:
    branches: 
      - main
      - dev
    paths:
      - '**'
      - '!README.md'
      - '!LICENSE'

  repository_dispatch: # Allows action to be triggered via webhook

  workflow_dispatch: # Allows action to be run manually from the Actions tab

jobs:
  build-debian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build Linux Image
        run: ./create_iso.sh      
      - name: Build Linux Image
        run: ls -la
      - name: get docs version
        run: echo "DEBIANVERSION=$(ls debian-*-modified* |  perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')-${{ github.ref_name	}}" >> $GITHUB_ENV
      - name: echo version
        run: echo ${{ env.DEBIANVERSION }}
      - uses: rickstaa/action-create-tag@v1
        continue-on-error: true
        id: tag_create_first
        with:
          tag: ${{ env.DEBIANVERSION }}
          tag_exists_error: true
          message: "${{ env.DEBIANVERSION }} release"
      - uses: dev-drprasad/delete-tag-and-release@v1.0 # PRERELEASE is v1.0 and can also be used to test and give us feedback
        if: ${{ steps.tag_create_first.outputs.tag_exists || steps.tag_create_first.outcome != 'success' }}
        with:
          tag_name: ${{ env.DEBIANVERSION }} #(required) tag name to delete 
          github_token: ${{ secrets.GITHUB_TOKEN }} # (required) a GitHub token with write access to the repo that needs to be modified
          delete_release: true #(optional) default: true 
      - uses: rickstaa/action-create-tag@v1
        id: tag_create_second
        with:
          tag: ${{ env.DEBIANVERSION }}
          force_push_tag: true
          message: "${{ env.DEBIANVERSION }} release"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}debian-*-amd64-modified.iso
          tag_name: ${{ env.DEBIANVERSION }}
          body: current debian ${{ env.DEBIANVERSION }}
          name: Release ${{ env.DEBIANVERSION }}